### ISSUE TITLE
[feature request] Add option to omit current file from MRU list

### ISSUE THREAD

**Issue by af** [tweekmonster/fzf-filemru#1]
Hi, 
What are your thoughts on adding an option to remove the current file from the MRU list? Since it's already open, I would never select it.

Thanks for a neat plugin, decent MRU support has been the one thing I've missed since switching to FZF.

**Comment by tweekmonster** [comment]
Woah, I'm not alone!  There are at least 5 of us according to the traffic graph!  :fist:

> What are your thoughts on adding an option to remove the current file from the MRU list? Since it's already open, I would never select it.

Never thought about it until you asked, but it makes sense.  I can add an `--exclude` flag to the shell script.  But, I think it could just be hard coded and not configurable on the condition that it excludes the file that's in the current buffer.  I still use FZF to select already-opened files that aren't in the current buffers, or to open the same file in a split.  What do you think?

**Comment by af** [comment]
I'm clearly biased, but I'd be fine with hardcoding it. I was only referring to the current buffer's file, I agree that files open in other buffers should not be excluded. 

Is there a use-case for selecting the current file? I can't think of any.

**Comment by tweekmonster** [comment]
> Is there a use-case for selecting the current file? I can't think of any.

I don't know.  I guess maybe if you wanted to quickly see what was last opened.  But, there's 5 of us, so it's not like it's going to be an earth shattering change.

**Comment by af** [comment]
Works great, thanks!
