### ISSUE TITLE
Looks like the fzf.vim refactor that just happened breaks this.

### ISSUE THREAD

**Issue by wadestuart** [tweekmonster/fzf-filemru#3]
Just a heads up that the latest fzf.vim refactor  (#6d1916197c24 - #5a088b242693) of the wrapper seems to break this.  Reproduce by running fzf.vim and this from head.

**Comment by tweekmonster** [comment]
Thanks.  Looks like it's just a deprecation for now.  I'll fix it so it works with the refactor a little later.

**Comment by wadestuart** [comment]
Yeah just wanted to give you a heads up -- up to this point it has been working fine to not pin either in my config.   The easy workaround is just to pin fzf.vim back before the refactor.

**Comment by tweekmonster** [comment]
@wadestuart Looks like it works with the refactor now.  Thanks again!
