### ISSUE TITLE
Ctrl-v and Ctrl-x does not work on Fzf-filemru

### ISSUE THREAD

**Issue by bfgasparin** [tweekmonster/fzf-filemru#5]
When listing my files using `:FilesMru`, and select the desired file, I type ctrl-v or ctrl-x to open it in a window, but it does not work. I could not found where is the problem.

When using any FZF vim command (https://github.com/junegunn/fzf.vim), it works.

Can anyone help?

**Comment by tweekmonster** [comment]
I'm not sure what the problem could be.  This plugin just passes through to FZF's common sink.  Maybe something has changed?  I don't have time to look into this now, but help is welcome.

**Comment by tweekmonster** [comment]
Fixed in #7
